### PR TITLE
Add example

### LINKED ISSUE #5: Rename SampleMain.cpp to LRUCache11.cpp
as the comment there suggest, this is a more complex set of examples/tests. 
Add (another) file `SampleMain.cpp` with the content from the section in Readme.

### PR DESCRIPTION
**Pull request by breznak**
- rename the test to LRUCache11Test.cpp
- add SampleMain.cpp + fix it

Fixes #5

### CODE REVIEW

**Comment by mohaps** [comment]
I have been meaning to add some more comprehensive examples and tests to this codebase. :) Thanks for hurrying that up

**Comment by ekg** [comment]
Something looks in conflict here. Mind resolving the conflict and pushing to your branch again? I think it will update the PR.

**Comment by breznak** [comment]
@mohaps done. I had to rebase and force push, please verify the change from your last PR to SampleMain is now in LRU..Test (as that is the copy/rename of the file) Thank you

**Comment by breznak** [comment]
Ping on the open PRs? This one is ready, on the other one I'd need help.

**Pull request merged**
