### PR TITLE
enable compilation on gcc 5.4 ubuntu

### PR DESCRIPTION
**Pull request by ekg**

### CODE REVIEW

**Comment by mohaps** [comment]
@ekg - better still, make a Makefile. I was going to make one. But I think a Makefile for the sample is a better idea

**Comment by ekg** [comment]
Sure can do.

**Comment by breznak** [comment]
Thanks @ekg for the PR, not only needed for gcc 5.4, but for gcc 4.8, clang 3.7 etc too! 
Fixes #6 for me :+1: 

@mohaps could you please merge this urgently? 
(and leave a Makefile to a separate PR? Personally, I don't see a reason for a Makefile, as the project's aim seems to be "being a single simple header file", so it is intended to be included into existing projects only as a header and using theirs (c)make files)

**Comment by mohaps** [comment]
Closing this as I updated the readme and the pull request for std::list implementation added the <mutex> include

**Pull request closed without merging**
